## Numpy:Package for Multidimensional array

### Vector (1D)

#### Matrix ( 2D or 3D )

##### Create an array 

In [10]:
import numpy as np

In [11]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [12]:
arr=np.array(simple_list)
arr

array([6, 7, 9])

In [18]:
arr=np.array([6,7,9])
arr

array([6, 7, 9])

In [13]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [15]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.arange(10,38)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

In [27]:
np.arange(10,83,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82])

In [21]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [28]:
type(np.zeros(6))

numpy.ndarray

In [29]:
type(np.zeros(6)[1])

numpy.float64

In [30]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [31]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [39]:
np.linspace(0,20,11,dtype=int)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [34]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [35]:
np.eye(5) ## Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
np.random.rand(2,4)

array([[0.29859705, 0.07793921, 0.15063758, 0.98602567],
       [0.30683965, 0.444345  , 0.75472512, 0.77654727]])

In [47]:
np.random.randn(2,4)

array([[ 0.70939009,  1.31060815, -2.0972561 ,  0.70803757],
       [-1.04174274, -1.55505633, -0.76931813,  0.6485178 ]])

In [46]:
np.random.rand(2,5)

array([[0.0429621 , 0.8986186 , 0.44741323, 0.82790066, 0.39725685],
       [0.43852254, 0.47618471, 0.13710034, 0.33919755, 0.74178864]])

In [42]:
np.random.randint(0,10,150)

array([9, 4, 9, 7, 6, 2, 6, 7, 3, 1, 1, 0, 0, 5, 9, 2, 9, 7, 1, 1, 6, 3,
       5, 8, 3, 8, 3, 7, 5, 3, 4, 1, 4, 8, 8, 5, 2, 4, 4, 5, 4, 4, 3, 8,
       6, 9, 6, 6, 8, 4, 1, 0, 9, 3, 8, 0, 9, 4, 5, 7, 1, 7, 1, 2, 9, 1,
       4, 7, 4, 8, 8, 1, 9, 8, 1, 6, 3, 0, 1, 3, 6, 2, 0, 3, 5, 8, 4, 0,
       4, 5, 5, 6, 6, 3, 1, 2, 1, 9, 9, 3, 7, 8, 5, 2, 8, 0, 1, 0, 6, 1,
       1, 2, 0, 2, 3, 7, 5, 9, 9, 9, 6, 5, 5, 0, 8, 7, 0, 5, 4, 3, 5, 1,
       7, 9, 7, 0, 0, 2, 9, 1, 1, 6, 7, 1, 3, 6, 7, 3, 9, 9])

In [43]:
np.random.randint(10,100,15)

array([75, 14, 47, 81, 95, 75, 85, 37, 85, 66, 70, 69, 67, 20, 37])

In [44]:
np.random.randint(20,56,100)

array([33, 44, 21, 31, 52, 52, 37, 27, 21, 32, 52, 46, 51, 34, 36, 34, 48,
       24, 38, 55, 54, 50, 53, 53, 44, 55, 40, 55, 49, 29, 47, 55, 48, 50,
       51, 32, 31, 31, 44, 28, 32, 44, 28, 51, 30, 37, 25, 21, 22, 43, 49,
       33, 46, 32, 37, 51, 51, 43, 30, 45, 43, 38, 46, 29, 26, 35, 49, 38,
       23, 41, 27, 34, 46, 53, 23, 38, 36, 25, 46, 38, 40, 40, 41, 28, 34,
       52, 38, 20, 53, 23, 23, 33, 50, 29, 52, 49, 22, 41, 54, 35])

In [48]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [49]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
rand_array=np.random.randint(0,10,5)
rand_array

array([2, 5, 1, 5, 5])

In [81]:
sample_array.min()

2

In [82]:
sample_array.argmin()

0

In [83]:
rand_array.argmin()

2

In [84]:
rand_array.min()

1

In [85]:
rand_array.max()

5

In [86]:
rand_array.argmax()

1

In [87]:
sample_array.argmax()

17

In [88]:
sample_array.dtype

dtype('int32')

In [89]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [90]:
a=np.random.rand(2,3)
a

array([[0.36291691, 0.4839196 , 0.19838107],
       [0.03779557, 0.34226674, 0.78242794]])

In [91]:
a.T

array([[0.36291691, 0.03779557],
       [0.4839196 , 0.34226674],
       [0.19838107, 0.78242794]])

In [98]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [99]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [100]:
sample_array=sample_array.reshape(3,4)
sample_array

ValueError: cannot reshape array of size 18 into shape (3,4)

In [101]:
sample_array=sample_array.reshape(9,2)
sample_array

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27]])

In [102]:
sample_array[5]=100
sample_array

array([[ 10,  11],
       [ 12,  13],
       [ 14,  15],
       [ 16,  17],
       [ 18,  19],
       [100, 100],
       [ 22,  23],
       [ 24,  25],
       [ 26,  27]])

In [103]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [104]:
sample_array[0:5]

array([10, 11, 12, 13, 14])

In [107]:
subset_sample_array=sample_array[4:7]
subset_sample_array

array([14, 15, 16])

In [108]:
sample_array[1:5]=1001
sample_array

array([  10, 1001, 1001, 1001, 1001,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99])

### Two-Dimensional arrays

In [ ]:
import numpy as np

In [109]:
sample_matrix=np.array([[24,13,2,15],[15,2,54,65],[56,76,24,7]])
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [110]:
sample_matrix[2][2]

24

In [111]:
sample_matrix[1][1]

2

In [112]:
sample_matrix[:,3] ## : means 'all'

array([15, 65,  7])

In [113]:
sample_matrix[2,2]

24

In [114]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [115]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [116]:
sample_matrix[2]

array([56, 76, 24,  7])

In [117]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [118]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [119]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [120]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [121]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [122]:
np.max(sample_array)

30

In [123]:
np.min(sample_array)

1

In [124]:
np.argmax(sample_array)

29

In [125]:
np.argmin(sample_array)

0

In [126]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [127]:
np.std(sample_array)

8.65544144839919

In [128]:
np.var(sample_array)

74.91666666666667

In [129]:
np.mean(sample_array)

15.5

In [134]:
array=np.random.randn(3,4) ### normal distribution
array

array([[-1.04453351,  1.17458155, -0.17378516,  1.31165897],
       [-0.37609785,  0.52253481,  1.77346039, -0.51537877],
       [ 2.01747227, -0.86338304,  0.5040726 , -0.51894419]])

In [135]:
np.round(array,decimals=3)

array([[-1.045,  1.175, -0.174,  1.312],
       [-0.376,  0.523,  1.773, -0.515],
       [ 2.017, -0.863,  0.504, -0.519]])

In [136]:
fruits=np.array(['apple','orange','mango','apple','orange'])
np.unique(fruits)

array(['apple', 'mango', 'orange'], dtype='<U6')